version: '3.1'

services:
     revoverflow-answer-service:
         image: 'revoverflow-answer-service:latest'
         build:
             context: .
             dockerfile: Dockerfile
         volumes:
             - '/answerservice'
             - '/root/.m2'
         ports:
             - '8083:8083'
